### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by dayadim** [gmdvdsp/fehdoku#1]
pls fix

**Comment by gmdvdsp** [comment]
> pls fix

hop on elden ring

**Comment by dayadim** [comment]
Thank you for the update!

Please await an update to this request. I will be available either,
- The evening of 21 May 2024, Tuesday
or,
- The evening of 22 May 2024, Wednesday
or, at the latest,
- The evening of 23 May 2024, Thursday.
